# Generated by Django 6.0.7 on 2026-07-16 10:36

import django.db.models.deletion
import lineaccounts.models
import uuid
from django.db import migrations, models


def seed_owner_singleton(apps, schema_editor):
    owner_account = apps.get_model('lineaccounts', 'OwnerAccount')
    owner_account.objects.get_or_create(slot=1, defaults={'state': 'vacant'})


def preserve_owner_singleton(apps, schema_editor):
    # Reverse migrationでaccount dataを個別に削除せず、table dropへ委ねる。
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linechannels', '0002_linechannel_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_id', models.CharField(max_length=64, validators=[lineaccounts.models.validate_identity_provider_id])),
                ('subject', models.CharField(max_length=33)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider_id', 'subject'), name='lineacct_identity_provider_subject_uniq')],
            },
        ),
        migrations.CreateModel(
            name='OwnerAccount',
            fields=[
                ('slot', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('vacant', 'Vacant'), ('active', 'Active'), ('deauthorization_pending', 'Deauthorization pending'), ('local_deletion_pending', 'Local deletion pending')], default='vacant', max_length=32)),
                ('unlink_generation', models.UUIDField(blank=True, editable=False, null=True)),
                ('line_deauthorized_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_account', to='lineaccounts.lineidentity')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lineaccounts.owneraccount')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('friendship_state', models.CharField(choices=[('friend', 'Friend'), ('not_friend', 'Not friend'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_recipients', to='linechannels.linechannel')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='lineaccounts.lineidentity')),
            ],
            options={
                'indexes': [models.Index(fields=['identity', 'enabled'], name='lineacct_recip_ident_en_idx')],
                'constraints': [models.UniqueConstraint(fields=('identity', 'line_channel'), name='lineacct_recipient_identity_channel_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='owneraccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot', 1)), name='lineacct_owner_singleton_slot'),
        ),
        migrations.AddConstraint(
            model_name='owneraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity__isnull', True), ('line_deauthorized_at__isnull', True), ('state', 'vacant'), ('unlink_generation__isnull', True)), models.Q(('identity__isnull', False), ('line_deauthorized_at__isnull', True), ('state', 'active'), ('unlink_generation__isnull', True)), models.Q(('identity__isnull', False), ('line_deauthorized_at__isnull', True), ('state', 'deauthorization_pending'), ('unlink_generation__isnull', False)), models.Q(('identity__isnull', False), ('line_deauthorized_at__isnull', False), ('state', 'local_deletion_pending'), ('unlink_generation__isnull', False)), _connector='OR'), name='lineacct_owner_state_consistent'),
        ),
        migrations.RunPython(seed_owner_singleton, preserve_owner_singleton),
    ]
