# Generated by Django 6.0.7 on 2026-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('formatted_text', models.TextField()),
                ('content_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('active_content_fingerprint', models.CharField(max_length=64, null=True, unique=True)),
                ('target_mode', models.CharField(choices=[('fixed_user', 'Fixed user')], default='fixed_user', max_length=32)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Unknown')], db_index=True, default='processing', max_length=16)),
                ('failure_type', models.CharField(blank=True, choices=[('configuration', 'Configuration'), ('invalid_request', 'Invalid request'), ('authentication', 'Authentication'), ('permission', 'Permission'), ('conflict', 'Conflict'), ('rate_limited', 'Rate limited'), ('service_unavailable', 'Service unavailable'), ('timeout_unknown', 'Timeout unknown'), ('processing_expired', 'Processing expired'), ('unexpected', 'Unexpected')], max_length=32, null=True)),
                ('line_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('line_accepted_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_at', models.DateTimeField()),
                ('processing_expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('target_mode', 'fixed_user')), name='delivery_target_mode_fixed_user'), models.CheckConstraint(condition=models.Q(models.Q(('active_content_fingerprint__isnull', False), ('completed_at__isnull', True), ('failed_at__isnull', True), ('failure_type__isnull', True), ('sent_at__isnull', True), ('status', 'processing')), models.Q(('active_content_fingerprint__isnull', True), ('completed_at__isnull', False), ('failed_at__isnull', True), ('failure_type__isnull', True), ('sent_at__isnull', False), ('status', 'succeeded')), models.Q(('active_content_fingerprint__isnull', True), ('completed_at__isnull', False), ('failed_at__isnull', False), ('failure_type__isnull', False), ('sent_at__isnull', True), ('status__in', ('failed', 'unknown'))), _connector='OR'), name='delivery_attempt_valid_state')],
            },
        ),
    ]
