# Generated by Django 6.0.7 on 2026-07-25

from django.db import migrations, models
from django.db.models import F


def backfill_legacy_delivery_scope(apps, schema_editor):
    attempt_model = apps.get_model("delivery", "DeliveryAttempt")
    identity_model = apps.get_model("lineaccounts", "LineIdentity")
    owner_model = apps.get_model("lineaccounts", "OwnerAccount")

    active_identity_ids = list(
        owner_model.objects.filter(
            slot=1,
            state="active",
            identity__isnull=False,
        ).values_list("identity_id", flat=True)[:2]
    )
    owner_identity_public_id = None
    if len(active_identity_ids) == 1:
        owner_identity_public_id = identity_model.objects.filter(
            id=active_identity_ids[0]
        ).values_list("public_id", flat=True).first()

    attempt_model.objects.update(
        owner_principal_slot=1,
        owner_identity_public_id=owner_identity_public_id,
        request_fingerprint=F("content_fingerprint"),
    )


def stop_reverse_with_linked_deliveries(apps, schema_editor):
    attempt_model = apps.get_model("delivery", "DeliveryAttempt")
    if attempt_model.objects.filter(target_mode="linked_recipient").exists():
        raise RuntimeError(
            "linked recipient delivery rows exist; "
            "automatic rollback would delete their owner and target snapshots"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("lineaccounts", "0002_friendship_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryattempt",
            name="active_request_fingerprint",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="request_fingerprint",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="channel_active_snapshot",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="channel_label_snapshot",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="channel_public_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="friendship_state_snapshot",
            field=models.CharField(
                choices=[
                    ("friend", "Friend"),
                    ("not_friend", "Not friend"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="owner_identity_public_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="owner_principal_slot",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="receipt_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="receipt_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="receipt_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="receipt_token_digest",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="receipt_webhook_event_id",
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="recipient_enabled_snapshot",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="recipient_public_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="failure_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("configuration", "Configuration"),
                    ("invalid_request", "Invalid request"),
                    ("authentication", "Authentication"),
                    ("permission", "Permission"),
                    ("conflict", "Conflict"),
                    ("rate_limited", "Rate limited"),
                    ("service_unknown", "Service unknown"),
                    ("service_unavailable", "Service unavailable"),
                    ("timeout_unknown", "Timeout unknown"),
                    ("response_unknown", "Response unknown"),
                    ("processing_expired", "Processing expired"),
                    ("target_changed", "Target changed"),
                    ("storage_unavailable", "Storage unavailable"),
                    ("unexpected", "Unexpected"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="target_mode",
            field=models.CharField(
                choices=[
                    ("fixed_user", "Fixed user"),
                    ("linked_recipient", "Linked recipient"),
                ],
                default="fixed_user",
                max_length=32,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="deliveryattempt",
            name="delivery_target_mode_fixed_user",
        ),
        migrations.RemoveConstraint(
            model_name="deliveryattempt",
            name="delivery_attempt_valid_state",
        ),
        migrations.RunPython(
            backfill_legacy_delivery_scope,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="deliveryattempt",
            index=models.Index(
                fields=["owner_principal_slot", "operation_id"],
                name="delivery_owner_operation_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("target_mode", "fixed_user"))
                    | models.Q(
                        ("channel_active_snapshot__isnull", False),
                        ("channel_label_snapshot__isnull", False),
                        ("channel_public_id__isnull", False),
                        (
                            "friendship_state_snapshot__in",
                            ("friend", "not_friend", "unknown"),
                        ),
                        ("friendship_state_snapshot__isnull", False),
                        ("owner_identity_public_id__isnull", False),
                        ("owner_principal_slot__isnull", False),
                        ("recipient_enabled_snapshot__isnull", False),
                        ("recipient_public_id__isnull", False),
                        ("request_fingerprint__isnull", False),
                        ("target_mode", "linked_recipient"),
                    )
                ),
                name="delivery_attempt_valid_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("failure_type__isnull", True),
                        ("sent_at__isnull", True),
                        ("status", "processing"),
                        models.Q(
                            models.Q(
                                ("active_content_fingerprint__isnull", False),
                                ("active_request_fingerprint__isnull", True),
                                ("target_mode", "fixed_user"),
                            ),
                            models.Q(
                                ("active_content_fingerprint__isnull", True),
                                (
                                    "active_request_fingerprint",
                                    models.F("request_fingerprint"),
                                ),
                                ("active_request_fingerprint__isnull", False),
                                ("target_mode", "linked_recipient"),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("active_content_fingerprint__isnull", True),
                        ("active_request_fingerprint__isnull", True),
                        ("completed_at__isnull", False),
                        ("failed_at__isnull", True),
                        ("failure_type__isnull", True),
                        ("sent_at__isnull", False),
                        ("status", "succeeded"),
                    ),
                    models.Q(
                        ("active_content_fingerprint__isnull", True),
                        ("active_request_fingerprint__isnull", True),
                        ("completed_at__isnull", False),
                        ("failed_at__isnull", False),
                        ("failure_type__isnull", False),
                        ("sent_at__isnull", True),
                        ("status__in", ("failed", "unknown")),
                    ),
                    _connector="OR",
                ),
                name="delivery_attempt_valid_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("receipt_confirmed_at__isnull", True),
                        ("receipt_expires_at__isnull", True),
                        ("receipt_requested", False),
                        ("receipt_token_digest__isnull", True),
                        ("receipt_webhook_event_id__isnull", True),
                    )
                    | (
                        models.Q(
                            ("receipt_expires_at__isnull", False),
                            ("receipt_requested", True),
                            ("receipt_token_digest__isnull", False),
                        )
                        & (
                            models.Q(
                                ("receipt_confirmed_at__isnull", True),
                                ("receipt_webhook_event_id__isnull", True),
                            )
                            | models.Q(
                                ("receipt_confirmed_at__isnull", False),
                                ("receipt_webhook_event_id__isnull", False),
                            )
                        )
                    )
                ),
                name="delivery_attempt_valid_receipt",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            stop_reverse_with_linked_deliveries,
        ),
    ]
