# Generated by Django 6.0.7 on 2026-07-28

from django.db import migrations, models
from django.db.models import F


def backfill_unified_active_fingerprint(apps, schema_editor):
    attempt_model = apps.get_model("delivery", "DeliveryAttempt")
    attempt_model.objects.filter(
        status="processing",
        active_request_fingerprint__isnull=True,
    ).update(
        active_request_fingerprint=F("active_content_fingerprint"),
    )


def restore_legacy_fingerprints(apps, schema_editor):
    attempt_model = apps.get_model("delivery", "DeliveryAttempt")
    attempt_model.objects.update(
        content_fingerprint=F("request_fingerprint"),
    )
    attempt_model.objects.filter(
        target_mode="fixed_user",
        status="processing",
    ).update(
        active_content_fingerprint=F("active_request_fingerprint"),
        active_request_fingerprint=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_linked_recipient_delivery"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliveryattempt",
            name="delivery_attempt_valid_state",
        ),
        migrations.RunPython(
            backfill_unified_active_fingerprint,
            restore_legacy_fingerprints,
        ),
        migrations.RemoveField(
            model_name="deliveryattempt",
            name="active_content_fingerprint",
        ),
        migrations.RemoveField(
            model_name="deliveryattempt",
            name="content_fingerprint",
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="request_fingerprint",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "active_request_fingerprint",
                            models.F("request_fingerprint"),
                        ),
                        ("active_request_fingerprint__isnull", False),
                        ("completed_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("failure_type__isnull", True),
                        ("sent_at__isnull", True),
                        ("status", "processing"),
                    ),
                    models.Q(
                        ("active_request_fingerprint__isnull", True),
                        ("completed_at__isnull", False),
                        ("failed_at__isnull", True),
                        ("failure_type__isnull", True),
                        ("sent_at__isnull", False),
                        ("status", "succeeded"),
                    ),
                    models.Q(
                        ("active_request_fingerprint__isnull", True),
                        ("completed_at__isnull", False),
                        ("failed_at__isnull", False),
                        ("failure_type__isnull", False),
                        ("sent_at__isnull", True),
                        ("status__in", ("failed", "unknown")),
                    ),
                    _connector="OR",
                ),
                name="delivery_attempt_valid_state",
            ),
        ),
    ]
