# Generated by Django 6.0.7 on 2026-07-15

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "messaging_api_channel_id",
                    models.CharField(max_length=64, unique=True),
                ),
                ("bot_user_id", models.CharField(max_length=33, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LineChannelCredential",
            fields=[
                ("access_token_ciphertext", models.BinaryField(editable=False)),
                ("channel_secret_ciphertext", models.BinaryField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="credential",
                        serialize=False,
                        to="linechannels.linechannel",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                "access_token_ciphertext"
                            ),
                            0,
                        ),
                        name="linechannels_access_ciphertext_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length(
                                "channel_secret_ciphertext"
                            ),
                            0,
                        ),
                        name="linechannels_secret_ciphertext_nonempty",
                    ),
                ]
            },
        ),
    ]
