# Generated by Django 6.0.7 on 2026-08-02 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedRichMenu',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_rich_menu_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('ownership_marker', models.CharField(max_length=128, unique=True)),
                ('lifecycle', models.CharField(choices=[('candidate', 'Candidate'), ('applied', 'Applied'), ('old', 'Old'), ('cleanup_required', 'Cleanup required'), ('deleted', 'Deleted'), ('released', 'Released')], max_length=32)),
                ('image_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linerichmenus_resource',
            },
        ),
        migrations.CreateModel(
            name='RichMenuChannelState',
            fields=[
                ('channel_public_id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_observation_kind', models.CharField(blank=True, choices=[('default_none', 'Default none'), ('managed_default', 'Managed default'), ('other_managed_default', 'Other managed default'), ('external_default', 'External default'), ('unknown', 'Unknown')], max_length=32, null=True)),
                ('last_observation_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_channel_states', to='linerichmenus.managedrichmenu')),
            ],
            options={
                'db_table': 'linerichmenus_channelstate',
            },
        ),
        migrations.AddField(
            model_name='managedrichmenu',
            name='channel_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_resources', to='linerichmenus.richmenuchannelstate'),
        ),
        migrations.CreateModel(
            name='RichMenuOperation',
            fields=[
                ('operation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('owner_identity_public_id', models.UUIDField()),
                ('provider_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('apply', 'Apply'), ('unlink', 'Unlink'), ('release', 'Release'), ('recheck', 'Recheck'), ('cleanup', 'Cleanup')], max_length=16)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('confirmation_usage_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expected_channel_revision', models.DateTimeField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('cleanup_required', 'Cleanup required'), ('recovery_active', 'Recovery active'), ('succeeded', 'Succeeded')], max_length=32)),
                ('stage', models.CharField(blank=True, choices=[('creating', 'Creating'), ('uploading', 'Uploading'), ('setting_default', 'Setting default'), ('verifying', 'Verifying'), ('clearing_default', 'Clearing default'), ('cleaning', 'Cleaning'), ('local_release', 'Local release')], max_length=32, null=True)),
                ('stage_started_at', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(max_length=64)),
                ('configuration_snapshot', models.JSONField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='linerichmenus.richmenuchannelstate')),
                ('subject_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_operations', to='linerichmenus.richmenuoperation')),
                ('target_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_operations', to='linerichmenus.managedrichmenu')),
            ],
            options={
                'db_table': 'linerichmenus_operation',
            },
        ),
        migrations.AddField(
            model_name='richmenuchannelstate',
            name='active_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_channel_states', to='linerichmenus.richmenuoperation'),
        ),
        migrations.AddField(
            model_name='richmenuchannelstate',
            name='blocking_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_channel_states', to='linerichmenus.richmenuoperation'),
        ),
        migrations.AddField(
            model_name='managedrichmenu',
            name='origin_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_resources', to='linerichmenus.richmenuoperation'),
        ),
        migrations.CreateModel(
            name='RichMenuOperationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('from_status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('cleanup_required', 'Cleanup required'), ('recovery_active', 'Recovery active'), ('succeeded', 'Succeeded')], max_length=32)),
                ('to_status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('cleanup_required', 'Cleanup required'), ('recovery_active', 'Recovery active'), ('succeeded', 'Succeeded')], max_length=32)),
                ('stage', models.CharField(choices=[('creating', 'Creating'), ('uploading', 'Uploading'), ('setting_default', 'Setting default'), ('verifying', 'Verifying'), ('clearing_default', 'Clearing default'), ('cleaning', 'Cleaning'), ('local_release', 'Local release')], max_length=32)),
                ('safe_reason', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='linerichmenus.richmenuoperation')),
            ],
            options={
                'db_table': 'linerichmenus_transition',
            },
        ),
        migrations.AddIndex(
            model_name='richmenuoperation',
            index=models.Index(fields=['channel_state', 'accepted_at'], name='lrm_op_channel_time_idx'),
        ),
        migrations.AddIndex(
            model_name='richmenuoperation',
            index=models.Index(fields=['subject_operation'], name='lrm_op_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='richmenuoperation',
            index=models.Index(fields=['target_resource'], name='lrm_op_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'apply'), ('subject_operation__isnull', True), ('target_resource__isnull', True)), models.Q(('kind__in', ('unlink', 'release')), ('subject_operation__isnull', True), ('target_resource__isnull', False)), models.Q(('kind', 'recheck'), ('subject_operation__isnull', False), ('target_resource__isnull', True)), models.Q(('kind', 'cleanup'), ('subject_operation__isnull', False), ('target_resource__isnull', False)), _connector='OR'), name='lrm_operation_relation_valid'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage__isnull', True), ('status', 'accepted')), models.Q(('stage__isnull', False), ('status__in', ('processing', 'failed', 'unknown', 'cleanup_required', 'recovery_active', 'succeeded'))), _connector='OR'), name='lrm_operation_stage_valid'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperation',
            constraint=models.CheckConstraint(condition=models.Q(('stage__isnull', True), ('stage__in', ('creating', 'uploading', 'setting_default', 'verifying', 'clearing_default', 'cleaning', 'local_release')), _connector='OR'), name='lrm_operation_stage_choice'),
        ),
        migrations.AddIndex(
            model_name='richmenuchannelstate',
            index=models.Index(fields=['blocking_operation'], name='lrm_state_block_idx'),
        ),
        migrations.AddIndex(
            model_name='richmenuchannelstate',
            index=models.Index(fields=['active_operation'], name='lrm_state_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='richmenuchannelstate',
            constraint=models.CheckConstraint(condition=models.Q(('last_observation_kind__isnull', True), ('last_observation_kind__in', ('default_none', 'managed_default', 'other_managed_default', 'external_default', 'unknown')), _connector='OR'), name='lrm_state_observation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='richmenuchannelstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('last_observation_fingerprint__isnull', True), ('last_observation_kind__isnull', True), ('last_observed_at__isnull', True)), models.Q(('last_observation_fingerprint__isnull', False), ('last_observation_kind__isnull', False), ('last_observed_at__isnull', False)), _connector='OR'), name='lrm_state_observation_complete'),
        ),
        migrations.AddIndex(
            model_name='managedrichmenu',
            index=models.Index(fields=['channel_state', 'lifecycle'], name='lrm_res_channel_life_idx'),
        ),
        migrations.AddConstraint(
            model_name='managedrichmenu',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ('candidate', 'applied', 'old', 'cleanup_required', 'deleted', 'released'))), name='lrm_resource_lifecycle_valid'),
        ),
        migrations.AddConstraint(
            model_name='managedrichmenu',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('lifecycle', 'deleted'), ('released_at__isnull', True)), models.Q(('deleted_at__isnull', True), ('lifecycle', 'released'), ('released_at__isnull', False)), models.Q(('deleted_at__isnull', True), ('lifecycle__in', ('candidate', 'applied', 'old', 'cleanup_required')), ('released_at__isnull', True)), _connector='OR'), name='lrm_resource_terminal_time_valid'),
        ),
        migrations.AddIndex(
            model_name='richmenuoperationtransition',
            index=models.Index(fields=['operation', 'created_at'], name='lrm_trans_op_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperationtransition',
            constraint=models.UniqueConstraint(fields=('operation', 'sequence'), name='lrm_transition_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperationtransition',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='lrm_transition_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperationtransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ['accepted', 'processing', 'failed', 'unknown', 'cleanup_required', 'recovery_active', 'succeeded'])), name='lrm_transition_from_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperationtransition',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['accepted', 'processing', 'failed', 'unknown', 'cleanup_required', 'recovery_active', 'succeeded'])), name='lrm_transition_to_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='richmenuoperationtransition',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['creating', 'uploading', 'setting_default', 'verifying', 'clearing_default', 'cleaning', 'local_release'])), name='lrm_transition_stage_valid'),
        ),
    ]
