# Generated by Django 6.0.7 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linerichmenus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedrichmenu",
            name="replacement_operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaced_resource",
                to="linerichmenus.richmenuoperation",
            ),
        ),
        migrations.AddConstraint(
            model_name="managedrichmenu",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lifecycle__in", ("candidate", "applied", "released")),
                        ("replacement_operation__isnull", True),
                    ),
                    ("lifecycle__in", ("old", "cleanup_required", "deleted")),
                    _connector="OR",
                ),
                name="lrm_resource_replacement_valid",
            ),
        ),
    ]
